services:
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: synctempo-pgadmin
    env_file:
      - .env.pgadmin
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - synctempo-pgadmin-data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  synctempo-pgadmin-data:
