CREATE TABLE calendario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    descricao VARCHAR(1000),
    cor VARCHAR(7) NOT NULL,
    criado_por_id BIGINT NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_calendario_criado_por FOREIGN KEY (criado_por_id) REFERENCES usuario (id),
    CONSTRAINT ck_calendario_cor CHECK (cor ~ '^#[0-9A-Fa-f]{6}$')
);

CREATE INDEX idx_calendario_criado_por ON calendario (criado_por_id);
