CREATE TABLE membro_calendario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendario_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    papel VARCHAR(10) NOT NULL,
    entrou_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_membro_calendario FOREIGN KEY (calendario_id) REFERENCES calendario (id) ON DELETE CASCADE,
    CONSTRAINT fk_membro_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id),
    CONSTRAINT uk_membro_calendario_usuario UNIQUE (calendario_id, usuario_id),
    CONSTRAINT ck_membro_papel CHECK (papel IN ('ADMIN', 'EDITOR', 'LEITOR'))
);

CREATE INDEX idx_membro_usuario ON membro_calendario (usuario_id);
