CREATE TABLE categoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendario_id BIGINT NOT NULL,
    nome VARCHAR(80) NOT NULL,
    cor VARCHAR(7) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_categoria_calendario FOREIGN KEY (calendario_id) REFERENCES calendario (id) ON DELETE CASCADE,
    CONSTRAINT uk_categoria_calendario_nome UNIQUE (calendario_id, nome),
    CONSTRAINT ck_categoria_cor CHECK (cor ~ '^#[0-9A-Fa-f]{6}$')
);
