CREATE TABLE evento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendario_id BIGINT NOT NULL,
    criado_por_id BIGINT NOT NULL,
    titulo VARCHAR(160) NOT NULL,
    descricao VARCHAR(4000),
    localizacao VARCHAR(255),
    link_reuniao VARCHAR(2048),
    data_evento DATE NOT NULL,
    hora_inicio TIME,
    hora_fim TIME,
    dia_inteiro BOOLEAN NOT NULL DEFAULT FALSE,
    visibilidade VARCHAR(20) NOT NULL DEFAULT 'DETALHADA',
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_evento_calendario FOREIGN KEY (calendario_id) REFERENCES calendario (id) ON DELETE CASCADE,
    CONSTRAINT fk_evento_criado_por FOREIGN KEY (criado_por_id) REFERENCES usuario (id),
    CONSTRAINT ck_evento_visibilidade CHECK (visibilidade IN ('DETALHADA', 'SOMENTE_OCUPADO')),
    CONSTRAINT ck_evento_horario CHECK (
        (dia_inteiro = TRUE AND hora_inicio IS NULL AND hora_fim IS NULL)
        OR (dia_inteiro = FALSE AND hora_inicio IS NOT NULL AND hora_fim IS NOT NULL AND hora_fim > hora_inicio)
    )
);

CREATE INDEX idx_evento_calendario_data ON evento (calendario_id, data_evento);
